project:
  type: website
  output-dir: docs

website:
  title: "Aabhas Gulati"
  navbar:
    right:
      - research.qmd
      - talks.qmd
      - blog.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css



